# Generated by Django 4.2.3 on 2023-07-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callhistory',
            name='Call_time',
            field=models.DurationField(null=True),
        ),
    ]
