# Generated by Django 4.2.3 on 2023-07-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_callhistory_call_time_callhistory_fx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callhistory',
            name='fx',
        ),
        migrations.AddField(
            model_name='callhistory',
            name='Call_time',
            field=models.DurationField(null=True),
        ),
    ]
