# Generated by Django 4.2.3 on 2023-07-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_callhistory_fx_callhistory_call_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='callhistory',
            name='call_recording',
            field=models.FileField(default=None, upload_to='call_recordings/'),
            preserve_default=False,
        ),
    ]
