# Generated by Django 4.2.3 on 2023-07-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_callhistory_call_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callhistory',
            name='call_recording',
            field=models.FileField(null=True, upload_to='call_recordings/'),
        ),
    ]
